##
## EPITECH PROJECT, 2020
## makefile
## File description:
## makefile
##

all:
	ln -s ./lib/my_trigo.py 108trigo
	chmod +x 108trigo

clean:
	rm -f 108trigo
	rm -rf lib/__pycache__

fclean: clean
	rm -f lib/*~

re:	fclean all
